### ISSUE TITLE
Katsana SDK v3 checklist

### ISSUE THREAD

**Issue by lutfime** [katsana/katsana-sdk-ios#2]
- [ ] Use Coder instead FastCoding
- [ ] Ensure cache working correctly
- [ ] Remove inherit from NSObject

Implement Tests
- [ ] Call API
- [ ] Cache
